# Generated by Django 5.0 on 2026-06-24 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_entidad_datadictionary_dataimportbatch_contacto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_PROCESO', 'En proceso'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=20)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=20)),
                ('fecha_apertura', models.DateTimeField()),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('sla_horas', models.PositiveIntegerField(default=48)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pgo_tickets', to=settings.AUTH_USER_MODEL)),
                ('entidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='core.entidad')),
                ('unidad_negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='core.unidadnegocio')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='TicketEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('COMENTARIO', 'Comentario'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('ASIGNACION', 'Asignación')], default='COMENTARIO', max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='pgo.ticket')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pgo_ticket_eventos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de ticket',
                'verbose_name_plural': 'Eventos de ticket',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PgoResultadoPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('periodo', models.CharField(help_text='YYYY-MM', max_length=7)),
                ('tickets_cerrados', models.PositiveIntegerField(default=0)),
                ('tickets_abiertos', models.PositiveIntegerField(default=0)),
                ('tiempo_promedio_horas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cumplimiento_sla_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('unidad_negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_pgo', to='core.unidadnegocio')),
            ],
            options={
                'verbose_name': 'Resultado PGO por período',
                'verbose_name_plural': 'Resultados PGO por período',
                'ordering': ['-periodo', 'unidad_negocio__nombre'],
                'unique_together': {('periodo', 'unidad_negocio')},
            },
        ),
    ]
