# Generated by Django 5.0 on 2026-07-30 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GerenciaScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('growth_cartera_f', models.FloatField(default=0.1)),
                ('growth_cartera_l', models.FloatField(default=0.08)),
                ('rate_activa_f', models.FloatField(default=0.18)),
                ('rate_activa_l', models.FloatField(default=0.14)),
                ('rate_pasiva_inv', models.FloatField(default=0.09)),
                ('rate_pasiva_bancos', models.FloatField(default=0.08)),
                ('growth_overhead', models.FloatField(default=0.05)),
                ('result_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gerencia_scenarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Escenario gerencial',
                'verbose_name_plural': 'Escenarios gerenciales',
                'ordering': ['-updated_at'],
            },
        ),
    ]
