# Generated by Django 5.0 on 2026-04-07 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("symbol", models.CharField(blank=True, max_length=10)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Moneda",
                "verbose_name_plural": "Monedas",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="MetricDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_scored", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Métrica",
                "verbose_name_plural": "Métricas",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="UNE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("FACTORING", "Factoraje"),
                            ("LEASING", "Leasing"),
                            ("INSURANCE", "Insurance"),
                            ("INVESTMENT", "Inversiones"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("name_es", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "UNE",
                "verbose_name_plural": "UNEs",
                "ordering": ["sort_order", "name_es"],
            },
        ),
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value_text", models.TextField(blank=True, null=True)),
                ("value_bool", models.BooleanField(blank=True, null=True)),
                ("value_json", models.JSONField(blank=True, null=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_system_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración del sistema",
                "verbose_name_plural": "Configuraciones del sistema",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="UNEAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("raw_value", models.CharField(max_length=255, unique=True)),
                ("alias_type", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "une",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="core.une",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alias de UNE",
                "verbose_name_plural": "Aliases de UNE",
                "ordering": ["raw_value"],
            },
        ),
    ]
