# Generated by Django 5.0 on 2026-04-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="une",
            name="default_amount_unit",
            field=models.CharField(
                choices=[
                    ("USD", "USD (dólares)"),
                    ("KUSD", "Miles de USD"),
                    ("GTQ", "GTQ (quetzales)"),
                    ("KGTQ", "Miles de GTQ"),
                ],
                default="KUSD",
                help_text="Unidad habitual de reporte para montos en esta UNE.",
                max_length=10,
            ),
        ),
    ]
