# Generated by Django 5.0 on 2026-06-24 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_une_default_amount_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('nit', models.CharField(blank=True, db_index=True, max_length=30)),
                ('tipo', models.CharField(choices=[('CLIENTE', 'Cliente'), ('PROSPECTO', 'Prospecto'), ('OTRO', 'Otro')], default='CLIENTE', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DataDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modulo', models.CharField(db_index=True, max_length=30)),
                ('tabla', models.CharField(max_length=80)),
                ('campo', models.CharField(max_length=80)),
                ('etiqueta', models.CharField(max_length=120)),
                ('tipo_dato', models.CharField(blank=True, max_length=40)),
                ('obligatorio', models.BooleanField(default=False)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Diccionario de datos',
                'verbose_name_plural': 'Diccionario de datos',
                'ordering': ['modulo', 'tabla', 'campo'],
                'unique_together': {('modulo', 'tabla', 'campo')},
            },
        ),
        migrations.CreateModel(
            name='DataImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modulo', models.CharField(choices=[('CRM', 'CRM'), ('RISK', 'Risk'), ('PGO', 'PGO'), ('PGC', 'PGC')], max_length=20)),
                ('tipo_importacion', models.CharField(max_length=80)),
                ('archivo_nombre', models.CharField(max_length=255)),
                ('filas_leidas', models.PositiveIntegerField(default=0)),
                ('creados', models.PositiveIntegerField(default=0)),
                ('actualizados', models.PositiveIntegerField(default=0)),
                ('errores', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('OK', 'OK'), ('PARTIAL', 'Parcial'), ('ERROR', 'Error')], default='PENDING', max_length=20)),
                ('log_texto', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lote de importación',
                'verbose_name_plural': 'Lotes de importación',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('cargo', models.CharField(blank=True, max_length=120)),
                ('es_principal', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='core.entidad')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['entidad__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='UnidadNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('activa', models.BooleanField(default=True)),
                ('une_pgc', models.ForeignKey(blank=True, help_text='Vínculo opcional con UNE existente del PGC.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_negocio_wcg', to='core.une')),
            ],
            options={
                'verbose_name': 'Unidad de negocio',
                'verbose_name_plural': 'Unidades de negocio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True)),
                ('unidad_negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='core.unidadnegocio')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='entidad',
            name='unidad_negocio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entidades', to='core.unidadnegocio'),
        ),
        migrations.CreateModel(
            name='RelacionEntidadProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_relacionados', to='core.entidad')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entidades_relacionadas', to='core.producto')),
            ],
            options={
                'verbose_name': 'Relación entidad-producto',
                'verbose_name_plural': 'Relaciones entidad-producto',
                'ordering': ['entidad__nombre', 'producto__nombre'],
                'unique_together': {('entidad', 'producto')},
            },
        ),
    ]
