# Generated by Django 5.0 on 2026-06-24 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_entidad_datadictionary_dataimportbatch_contacto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoCobranza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_cobranza', to='core.entidad')),
            ],
            options={
                'verbose_name': 'Contacto de cobranza',
                'verbose_name_plural': 'Contactos de cobranza',
                'ordering': ['entidad__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('periodo', models.CharField(help_text='YYYY-MM', max_length=7)),
                ('saldo_total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('mora_dias', models.PositiveIntegerField(default=0)),
                ('exposicion', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('notas', models.TextField(blank=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_financieros', to='core.entidad')),
            ],
            options={
                'verbose_name': 'Estado financiero',
                'verbose_name_plural': 'Estados financieros',
                'ordering': ['-periodo', 'entidad__nombre'],
                'unique_together': {('entidad', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='PagoRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referencia', models.CharField(max_length=80)),
                ('fecha_pago', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=16)),
                ('moneda', models.CharField(default='GTQ', max_length=3)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_realizados', to='core.entidad')),
            ],
            options={
                'verbose_name': 'Pago realizado',
                'verbose_name_plural': 'Pagos realizados',
                'ordering': ['-fecha_pago'],
                'unique_together': {('entidad', 'referencia')},
            },
        ),
        migrations.CreateModel(
            name='ProgramacionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referencia', models.CharField(max_length=80)),
                ('fecha_programada', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=16)),
                ('moneda', models.CharField(default='GTQ', max_length=3)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaciones_pago', to='core.entidad')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programaciones_pago', to='core.producto')),
            ],
            options={
                'verbose_name': 'Programación de pago',
                'verbose_name_plural': 'Programaciones de pago',
                'ordering': ['fecha_programada'],
                'unique_together': {('entidad', 'referencia')},
            },
        ),
        migrations.CreateModel(
            name='RiskOperationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referencia_operacion', models.CharField(db_index=True, max_length=80)),
                ('fecha_snapshot', models.DateField()),
                ('nivel_riesgo', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto'), ('CRITICO', 'Crítico')], default='MEDIO', max_length=20)),
                ('dias_mora', models.PositiveIntegerField(default=0)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('alerta', models.BooleanField(default=False)),
                ('detalle', models.TextField(blank=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_snapshots', to='core.entidad')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_snapshots', to='core.producto')),
            ],
            options={
                'verbose_name': 'Snapshot operativo de riesgo',
                'verbose_name_plural': 'Snapshots operativos de riesgo',
                'ordering': ['-fecha_snapshot', 'entidad__nombre'],
                'unique_together': {('entidad', 'referencia_operacion', 'fecha_snapshot')},
            },
        ),
    ]
