# Generated by Django 5.0 on 2026-06-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskoperationsnapshot',
            name='monto_exigible',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto vencido/exigible al momento del snapshot.', max_digits=16),
        ),
    ]
