# Generated by Django 5.0 on 2026-04-07 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FileUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("original_filename", models.CharField(max_length=255)),
                ("stored_file", models.FileField(upload_to="uploads/")),
                (
                    "file_type_detected",
                    models.CharField(
                        choices=[
                            ("FINANCIAL", "Estado financiero (WC*)"),
                            ("NEW_CLIENTS", "Clientes nuevos"),
                            ("CROSS_SALE", "Venta cruzada"),
                            ("STATION_TIMES", "Tiempos de estaciones"),
                            ("UNKNOWN", "Desconocido"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                (
                    "file_format",
                    models.CharField(
                        choices=[
                            ("XLSX", "Excel (.xlsx)"),
                            ("CSV", "CSV"),
                            ("TSV", "TSV"),
                            ("OTHER", "Otro"),
                        ],
                        default="OTHER",
                        max_length=10,
                    ),
                ),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("file_size_bytes", models.BigIntegerField(default=0)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("detected_year", models.PositiveIntegerField(blank=True, null=True)),
                ("detected_month", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "Subido"),
                            ("PARSED_OK", "Parseado OK"),
                            ("PARSED_ERROR", "Error al parsear"),
                        ],
                        default="UPLOADED",
                        max_length=20,
                    ),
                ),
                ("error_summary", models.TextField(blank=True)),
                ("parsing_notes", models.TextField(blank=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Archivo subido",
                "verbose_name_plural": "Archivos subidos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FileImportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("step_code", models.CharField(blank=True, max_length=100)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                        ],
                        default="INFO",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("line_number", models.PositiveIntegerField(blank=True, null=True)),
                ("payload_json", models.JSONField(blank=True, null=True)),
                (
                    "file_upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="imports.fileupload",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de importación",
                "verbose_name_plural": "Logs de importación",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CrossSaleImportHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveIntegerField()),
                (
                    "file_upload",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cross_sales_header",
                        to="imports.fileupload",
                    ),
                ),
            ],
            options={
                "verbose_name": "Encabezado ventas cruzadas",
                "verbose_name_plural": "Encabezados ventas cruzadas",
                "unique_together": {("year", "month")},
            },
        ),
        migrations.CreateModel(
            name="FinancialStatementImportHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveIntegerField()),
                ("statement_type", models.CharField(default="ER", max_length=50)),
                ("source_sheet_name", models.CharField(blank=True, max_length=50)),
                ("source_entity_name", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                (
                    "file_upload",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_header",
                        to="imports.fileupload",
                    ),
                ),
                (
                    "une",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_imports",
                        to="core.une",
                    ),
                ),
            ],
            options={
                "verbose_name": "Encabezado estado financiero",
                "verbose_name_plural": "Encabezados estados financieros",
                "unique_together": {("une", "year", "month", "statement_type")},
            },
        ),
        migrations.CreateModel(
            name="NewClientImportHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveIntegerField()),
                (
                    "file_upload",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_clients_header",
                        to="imports.fileupload",
                    ),
                ),
            ],
            options={
                "verbose_name": "Encabezado clientes nuevos",
                "verbose_name_plural": "Encabezados clientes nuevos",
                "unique_together": {("year", "month")},
            },
        ),
        migrations.CreateModel(
            name="StationTimeImportHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveIntegerField()),
                (
                    "file_upload",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="station_times_header",
                        to="imports.fileupload",
                    ),
                ),
            ],
            options={
                "verbose_name": "Encabezado tiempos estaciones",
                "verbose_name_plural": "Encabezados tiempos estaciones",
                "unique_together": {("year", "month")},
            },
        ),
    ]
