# Generated by Django 5.0 on 2026-04-07 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fileimportlog",
            options={"ordering": ["created_at"]},
        ),
    ]
