# Generated by Django 5.0 on 2026-04-12 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_une_default_amount_unit"),
        ("imports", "0002_alter_fileimportlog_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewClientImportRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveIntegerField()),
                ("client_name", models.CharField(blank=True, max_length=255)),
                ("nit", models.CharField(blank=True, max_length=50)),
                ("operation_code", models.CharField(blank=True, max_length=100)),
                ("previous_contracts", models.IntegerField(default=0)),
                ("counts_as_new", models.BooleanField(default=False)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "source_row_number",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("raw_une_value", models.CharField(blank=True, max_length=255)),
                ("observations", models.TextField(blank=True)),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="new_client_import_rows",
                        to="core.currency",
                    ),
                ),
                (
                    "header",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="imports.newclientimportheader",
                    ),
                ),
                (
                    "une",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_client_import_rows",
                        to="core.une",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle importado de cliente nuevo",
                "verbose_name_plural": "Detalles importados de clientes nuevos",
                "ordering": [
                    "year",
                    "month",
                    "une__sort_order",
                    "client_name",
                    "operation_code",
                ],
            },
        ),
    ]
