# Generated by Django 5.0 on 2026-04-15 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_une_default_amount_unit"),
        ("imports", "0003_newclientimportrow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileupload",
            name="status",
            field=models.CharField(
                choices=[
                    ("UPLOADED", "P1. Archivo listo para lectura"),
                    ("PARSED_OK", "P2. Datos cargados correctamente"),
                    ("PARSED_ERROR", "E1. Error al leer los datos"),
                ],
                default="UPLOADED",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CrossSaleImportRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveIntegerField()),
                ("client_name", models.CharField(blank=True, max_length=255)),
                ("operation_code", models.CharField(blank=True, max_length=100)),
                ("date", models.DateField(blank=True, null=True)),
                ("raw_une_destination", models.CharField(blank=True, max_length=255)),
                ("raw_une_origin", models.CharField(blank=True, max_length=255)),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cross_sale_rows",
                        to="core.currency",
                    ),
                ),
                (
                    "header",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="imports.crosssaleimportheader",
                    ),
                ),
                (
                    "une_destination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cross_sales_received",
                        to="core.une",
                    ),
                ),
                (
                    "une_origin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cross_sales_sent",
                        to="core.une",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle venta cruzada",
                "verbose_name_plural": "Detalles venta cruzada",
            },
        ),
    ]
