# Generated by Django 5.0 on 2026-07-15 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0004_alter_fileupload_status_crosssaleimportrow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileimportlog',
            options={'ordering': ['created_at'], 'verbose_name': 'Log de importación', 'verbose_name_plural': 'Logs de importación'},
        ),
    ]
