# Generated by Django 5.2.15 on 2026-06-24 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_producto', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UnidadNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Unidad de negocio',
                'verbose_name_plural': 'Unidades de negocio',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='DataDictionaryField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(db_index=True, max_length=50)),
                ('nombre_logico', models.CharField(max_length=150)),
                ('tabla_fisica', models.CharField(max_length=100)),
                ('campo_fisico', models.CharField(max_length=100)),
                ('tipo_dato', models.CharField(blank=True, max_length=50)),
                ('definicion', models.TextField(blank=True)),
                ('fuente', models.CharField(blank=True, max_length=255)),
                ('periodicidad', models.CharField(blank=True, max_length=50)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Campo de diccionario de datos',
                'verbose_name_plural': 'Diccionario de datos',
                'ordering': ['modulo', 'orden', 'tabla_fisica', 'campo_fisico'],
                'constraints': [models.UniqueConstraint(fields=('tabla_fisica', 'campo_fisico'), name='uniq_data_dictionary_tabla_campo')],
            },
        ),
        migrations.CreateModel(
            name='DataImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(db_index=True, max_length=50)),
                ('tipo_importacion', models.CharField(max_length=100)),
                ('archivo_nombre', models.CharField(max_length=255)),
                ('archivo_hash', models.CharField(blank=True, max_length=128)),
                ('archivo_ruta', models.CharField(blank=True, max_length=500)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('filas_leidas', models.PositiveIntegerField(default=0)),
                ('filas_validas', models.PositiveIntegerField(default=0)),
                ('filas_error', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('ok', 'OK'), ('parcial', 'Parcial'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wcgone_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lote de importación',
                'verbose_name_plural': 'Lotes de importación',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='DataImportError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila_numero', models.PositiveIntegerField()),
                ('campo', models.CharField(blank=True, max_length=100)),
                ('valor_original', models.TextField(blank=True)),
                ('mensaje_error', models.TextField()),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errores', to='wcgone_core.dataimportbatch')),
            ],
            options={
                'verbose_name': 'Error de importación',
                'verbose_name_plural': 'Errores de importación',
                'ordering': ['batch', 'fila_numero'],
            },
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_entidad', models.CharField(choices=[('cliente', 'Cliente'), ('inversionista', 'Inversionista'), ('ambos', 'Ambos'), ('proveedor', 'Proveedor'), ('otro', 'Otro')], default='cliente', max_length=30)),
                ('es_persona', models.BooleanField(default=False)),
                ('nombre', models.CharField(db_index=True, max_length=255)),
                ('nombre_comercial', models.CharField(blank=True, max_length=255)),
                ('nit', models.CharField(blank=True, db_index=True, max_length=50)),
                ('pais', models.CharField(blank=True, max_length=100)),
                ('departamento', models.CharField(blank=True, max_length=100)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('direccion_fiscal', models.TextField(blank=True)),
                ('direccion_operativa', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('sector_economico', models.CharField(blank=True, max_length=150)),
                ('codigo_sector', models.CharField(blank=True, max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('categoria_riesgo', models.CharField(blank=True, max_length=50)),
                ('origen', models.CharField(blank=True, max_length=100)),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['activo', 'tipo_entidad'], name='core_entida_activo_203f70_idx')],
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cargo', models.CharField(blank=True, max_length=150)),
                ('area', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('telefono_movil', models.CharField(blank=True, max_length=50)),
                ('telefono_oficina', models.CharField(blank=True, max_length=50)),
                ('extension', models.CharField(blank=True, max_length=20)),
                ('es_decisor_credito', models.BooleanField(default=False)),
                ('es_contacto_cobranza', models.BooleanField(default=False)),
                ('es_contacto_operativo', models.BooleanField(default=False)),
                ('nivel_influencia', models.CharField(blank=True, max_length=50)),
                ('nivel_apertura', models.CharField(blank=True, max_length=50)),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='wcgone_core.entidad')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['entidad__nombre', 'nombre'],
                'indexes': [models.Index(fields=['entidad', 'activo'], name='core_contac_entidad_bca52e_idx')],
            },
        ),
        migrations.CreateModel(
            name='RelacionEntidadProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=50)),
                ('monto_aprobado', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('moneda', models.CharField(blank=True, max_length=10)),
                ('codigo_operacion_externo', models.CharField(blank=True, db_index=True, max_length=100)),
                ('notas', models.TextField(blank=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_producto', to='wcgone_core.entidad')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relaciones_entidad', to='wcgone_core.producto')),
                ('unidad_negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relaciones_entidad_producto', to='wcgone_core.unidadnegocio')),
            ],
            options={
                'verbose_name': 'Relación entidad-producto',
                'verbose_name_plural': 'Relaciones entidad-producto',
                'ordering': ['entidad__nombre', 'producto__nombre'],
                'indexes': [models.Index(fields=['entidad', 'producto'], name='core_relaci_entidad_efa06a_idx')],
            },
        ),
    ]
