# Generated by Django 5.0 on 2026-07-15 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wcgone_core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contacto',
            new_name='wcgone_core_entidad_0ae482_idx',
            old_name='core_contac_entidad_bca52e_idx',
        ),
        migrations.RenameIndex(
            model_name='entidad',
            new_name='wcgone_core_activo_81ca2e_idx',
            old_name='core_entida_activo_203f70_idx',
        ),
        migrations.RenameIndex(
            model_name='relacionentidadproducto',
            new_name='wcgone_core_entidad_7c414b_idx',
            old_name='core_relaci_entidad_efa06a_idx',
        ),
    ]
