# Generated by Django 5.0 on 2026-07-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='default', max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('include_admin_by_default', models.BooleanField(default=False)),
                ('include_pgc_by_default', models.BooleanField(default=True)),
                ('include_pgo_by_default', models.BooleanField(default=False)),
                ('include_risk_by_default', models.BooleanField(default=False)),
                ('include_executive_summary', models.BooleanField(default=True)),
                ('include_period_comparison', models.BooleanField(default=True)),
                ('include_ai_section', models.BooleanField(default=True)),
                ('compact_mode', models.BooleanField(default=True, help_text='Limita tablas y listas a hallazgos de alta densidad.')),
                ('max_table_rows', models.PositiveIntegerField(default=25)),
                ('intro_note', models.TextField(blank=True, help_text='Nota opcional al inicio de cada reporte de resultados.')),
            ],
            options={
                'verbose_name': 'Configuración de reportes',
                'verbose_name_plural': 'Configuraciones de reportes',
            },
        ),
    ]
