# Generated by Django 5.0 on 2026-04-07 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_une_default_amount_unit"),
    ]

    operations = [
        migrations.CreateModel(
            name="PGCPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.PositiveIntegerField(unique=True)),
                ("name", models.CharField(default="Plan PGC", max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Plan PGC",
                "verbose_name_plural": "Planes PGC",
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveIntegerField()),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                ("points_if_achieved", models.PositiveIntegerField(default=0)),
                (
                    "reference_annual_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Solo referencia; no asigna puntos por sí misma.",
                        max_digits=18,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_targets",
                        to="core.metricdefinition",
                    ),
                ),
                (
                    "une",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_targets",
                        to="core.une",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_targets",
                        to="pgc.pgcplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meta mensual",
                "verbose_name_plural": "Metas mensuales",
                "ordering": ["year", "month", "une__sort_order", "metric__code"],
                "unique_together": {("plan", "une", "metric", "year", "month")},
            },
        ),
        migrations.CreateModel(
            name="MonthlyScorecard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveIntegerField()),
                ("total_points", models.PositiveIntegerField(default=0)),
                ("qualified_threshold", models.PositiveIntegerField(default=80)),
                ("is_month_qualified", models.BooleanField(default=False)),
                ("summary_note", models.TextField(blank=True)),
                (
                    "une",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scorecards",
                        to="core.une",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scorecards",
                        to="pgc.pgcplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Score mensual",
                "verbose_name_plural": "Scores mensuales",
                "ordering": ["year", "month", "une__sort_order"],
                "unique_together": {("plan", "une", "year", "month")},
            },
        ),
        migrations.CreateModel(
            name="MonthlyMetricResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveIntegerField()),
                (
                    "measured_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                ("is_achieved", models.BooleanField(default=False)),
                ("points_awarded", models.PositiveIntegerField(default=0)),
                ("calculation_note", models.TextField(blank=True)),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metric_results",
                        to="core.metricdefinition",
                    ),
                ),
                (
                    "une",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metric_results",
                        to="core.une",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metric_results",
                        to="pgc.pgcplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado mensual de métrica",
                "verbose_name_plural": "Resultados mensuales de métricas",
                "ordering": ["year", "month", "une__sort_order", "metric__code"],
                "unique_together": {("plan", "une", "metric", "year", "month")},
            },
        ),
        migrations.CreateModel(
            name="ManualRequirementsCompliance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveIntegerField()),
                ("is_compliant", models.BooleanField(default=True)),
                ("incident_note", models.TextField(blank=True)),
                (
                    "une",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manual_requirements",
                        to="core.une",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manual_requirements",
                        to="pgc.pgcplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cumplimiento manual de requerimientos",
                "verbose_name_plural": "Cumplimientos manuales de requerimientos",
                "ordering": ["year", "month", "une__sort_order"],
                "unique_together": {("plan", "une", "year", "month")},
            },
        ),
    ]
