# Generated by Django 5.0 on 2026-04-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pgc", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveIntegerField()),
                ("usd_to_gtq", models.DecimalField(decimal_places=5, max_digits=10)),
            ],
            options={
                "ordering": ["year", "month"],
                "unique_together": {("year", "month")},
            },
        ),
    ]
