# Generated by Django 5.0 on 2026-05-19 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_une_default_amount_unit"),
        ("pgc", "0002_monthly_exchange_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricReserve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[("modo1", "Modo 1"), ("modo2", "Modo 2")],
                        default="modo2",
                        max_length=10,
                    ),
                ),
                ("source_year", models.PositiveIntegerField()),
                ("source_month", models.PositiveIntegerField()),
                (
                    "amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "remaining",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metricreserves",
                        to="core.metricdefinition",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metricreserves",
                        to="pgc.pgcplan",
                    ),
                ),
                (
                    "une",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metricreserves",
                        to="core.une",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "source_year",
                    "source_month",
                    "une__sort_order",
                    "metric__code",
                ],
            },
        ),
        migrations.CreateModel(
            name="MonthlyMetricScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveIntegerField()),
                (
                    "mode",
                    models.CharField(
                        choices=[("modo1", "Modo 1"), ("modo2", "Modo 2")],
                        default="modo1",
                        max_length=10,
                    ),
                ),
                (
                    "measuredvalue",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "targetvalue",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("isachieved", models.BooleanField(default=False)),
                (
                    "pointsawarded",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "carryin",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "carryused",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "carrygenerated",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                ("calculationnote", models.TextField(blank=True)),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metricscores",
                        to="core.metricdefinition",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metricscores",
                        to="pgc.pgcplan",
                    ),
                ),
                (
                    "une",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metricscores",
                        to="core.une",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "year",
                    "month",
                    "une__sort_order",
                    "metric__code",
                    "mode",
                ],
                "unique_together": {("plan", "une", "metric", "year", "month", "mode")},
            },
        ),
        migrations.CreateModel(
            name="MonthlyModeScorecard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveIntegerField()),
                (
                    "mode",
                    models.CharField(
                        choices=[("modo1", "Modo 1"), ("modo2", "Modo 2")],
                        default="modo1",
                        max_length=10,
                    ),
                ),
                (
                    "totalpoints",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "qualifiedthreshold",
                    models.DecimalField(decimal_places=4, default=80, max_digits=18),
                ),
                ("ismonthqualified", models.BooleanField(default=False)),
                ("summarynote", models.TextField(blank=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modescorecards",
                        to="pgc.pgcplan",
                    ),
                ),
                (
                    "une",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modescorecards",
                        to="core.une",
                    ),
                ),
            ],
            options={
                "ordering": ["year", "month", "une__sort_order", "mode"],
                "unique_together": {("plan", "une", "year", "month", "mode")},
            },
        ),
    ]
