# Generated by Django 5.0 on 2026-08-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgc', '0006_monthlymetricresult_income_conversion_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvLiveChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField()),
                ('ext', models.CharField(max_length=4)),
                ('content', models.BinaryField()),
                ('stamp', models.CharField(blank=True, default='', max_length=32)),
                ('byte_size', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chart TV vivo (respaldo)',
                'verbose_name_plural': 'Charts TV vivos (respaldo)',
                'ordering': ['slot', 'ext'],
                'unique_together': {('slot', 'ext')},
            },
        ),
    ]
