# Generated by Django 5.2.15 on 2026-06-24 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wcgone_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaEntidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_notas_entidad', to=settings.AUTH_USER_MODEL)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_entidad', to='wcgone_core.entidad')),
            ],
            options={
                'verbose_name': 'Nota de entidad',
                'verbose_name_plural': 'Notas de entidad',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Interaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('tipo_interaccion', models.CharField(db_index=True, max_length=50)),
                ('resumen', models.CharField(max_length=255)),
                ('resultado', models.TextField(blank=True)),
                ('seguimiento_requerido', models.BooleanField(default=False)),
                ('notas', models.TextField(blank=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='wcgone_core.entidad')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wcgone_crm_interacciones', to='wcgone_core.dataimportbatch')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interacciones', to='wcgone_core.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wcgone_crm_interacciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interacción',
                'verbose_name_plural': 'Interacciones',
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['entidad', 'fecha'], name='crm_interac_entidad_d26d43_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(blank=True, max_length=20)),
                ('estado', models.CharField(default='pendiente', max_length=30)),
                ('completada', models.BooleanField(default=False)),
                ('fecha_completada', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wcgone_crm_tareas', to=settings.AUTH_USER_MODEL)),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='wcgone_core.contacto')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='wcgone_core.entidad')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['completada', 'fecha_limite', '-id'],
                'indexes': [models.Index(fields=['completada', 'fecha_limite'], name='crm_tarea_complet_2d7e2b_idx'), models.Index(fields=['entidad', 'estado'], name='crm_tarea_entidad_2c4d7f_idx')],
            },
        ),
    ]
