# Generated by Django 5.0 on 2026-07-15 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wcgone_crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='interaccion',
            new_name='wcgone_crm__entidad_eb2333_idx',
            old_name='crm_interac_entidad_d26d43_idx',
        ),
        migrations.RenameIndex(
            model_name='tarea',
            new_name='wcgone_crm__complet_8fa3ca_idx',
            old_name='crm_tarea_complet_2d7e2b_idx',
        ),
        migrations.RenameIndex(
            model_name='tarea',
            new_name='wcgone_crm__entidad_64662c_idx',
            old_name='crm_tarea_entidad_2c4d7f_idx',
        ),
    ]
