# Generated by Django 5.2.15 on 2026-06-24 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wcgone_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PgoMetricRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('variable', models.CharField(max_length=100)),
                ('criterio', models.TextField()),
                ('puntos', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('peso', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('tipo_regla', models.CharField(choices=[('automatica', 'Automática'), ('manual', 'Manual'), ('hibrida', 'Híbrida')], default='automatica', max_length=20)),
                ('formula_texto', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('unidad_negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pgo_reglas', to='wcgone_core.unidadnegocio')),
            ],
            options={
                'verbose_name': 'Regla métrica PGO',
                'verbose_name_plural': 'Reglas métricas PGO',
                'ordering': ['area', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='PgoPeriodScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(db_index=True, max_length=7)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('puntaje_total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('clasifica', models.BooleanField(default=False)),
                ('detalle_json', models.JSONField(blank=True, default=dict)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('unidad_negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wcgone_pgo_period_scores', to='wcgone_core.unidadnegocio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wcgone_pgo_period_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Puntaje PGO por período',
                'verbose_name_plural': 'Puntajes PGO por período',
                'ordering': ['-periodo', 'area'],
            },
        ),
        migrations.CreateModel(
            name='PgoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_externo_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('usuario_solicita', models.CharField(blank=True, max_length=150)),
                ('correo_solicita', models.EmailField(blank=True, max_length=254)),
                ('departamento', models.CharField(blank=True, db_index=True, max_length=150)),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('titulo', models.CharField(max_length=255)),
                ('estado_raw', models.CharField(blank=True, max_length=100)),
                ('estado_normalizado', models.CharField(blank=True, db_index=True, max_length=50)),
                ('solucion', models.TextField(blank=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('fecha_apertura', models.DateTimeField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('prioridad', models.CharField(blank=True, db_index=True, max_length=50)),
                ('tipo_servicio', models.CharField(blank=True, max_length=100)),
                ('razon_cierre', models.CharField(blank=True, max_length=255)),
                ('sistema', models.CharField(blank=True, db_index=True, max_length=100)),
                ('elemento', models.CharField(blank=True, max_length=255)),
                ('ruta', models.CharField(blank=True, max_length=255)),
                ('anio_mes', models.CharField(blank=True, db_index=True, max_length=7)),
                ('duracion_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sla_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sla_cumplido', models.BooleanField(default=False)),
                ('payload_raw_json', models.JSONField(blank=True, default=dict)),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wcgone_pgo_tickets', to='wcgone_core.dataimportbatch')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wcgone_pgo_tickets', to=settings.AUTH_USER_MODEL)),
                ('unidad_negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wcgone_pgo_tickets', to='wcgone_core.unidadnegocio')),
            ],
            options={
                'verbose_name': 'Ticket PGO',
                'verbose_name_plural': 'Tickets PGO',
                'ordering': ['-fecha_apertura', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PgoMonthlyAgg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(db_index=True, max_length=7)),
                ('departamento', models.CharField(blank=True, max_length=150)),
                ('tickets_recibidos', models.PositiveIntegerField(default=0)),
                ('tickets_cerrados', models.PositiveIntegerField(default=0)),
                ('tiempo_promedio_horas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sla_cumplidos', models.PositiveIntegerField(default=0)),
                ('sla_incumplidos', models.PositiveIntegerField(default=0)),
                ('tickets_abiertos_fin_mes', models.PositiveIntegerField(default=0)),
                ('unidad_negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pgo_monthly_aggs', to='wcgone_core.unidadnegocio')),
            ],
            options={
                'verbose_name': 'Agregado mensual PGO',
                'verbose_name_plural': 'Agregados mensuales PGO',
                'ordering': ['-periodo', 'unidad_negocio__nombre'],
                'indexes': [models.Index(fields=['periodo', 'departamento'], name='pgo_pgomont_periodo_f560c7_idx')],
            },
        ),
    ]
