# Generated by Django 5.0 on 2026-07-15 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wcgone_pgo', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pgomonthlyagg',
            new_name='wcgone_pgo__periodo_5378a8_idx',
            old_name='pgo_pgomont_periodo_f560c7_idx',
        ),
    ]
