# Generated by Django 5.2.15 on 2026-06-24 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wcgone_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_operacion', models.CharField(db_index=True, max_length=100)),
                ('contrato_numero', models.CharField(blank=True, db_index=True, max_length=100)),
                ('asesor', models.CharField(blank=True, max_length=150)),
                ('moneda', models.CharField(blank=True, max_length=10)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('monto_original', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('estado', models.CharField(blank=True, max_length=50)),
                ('notas', models.TextField(blank=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operaciones_riesgo', to='wcgone_core.entidad')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operaciones_riesgo', to='wcgone_core.producto')),
                ('unidad_negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operaciones_riesgo', to='wcgone_core.unidadnegocio')),
            ],
            options={
                'verbose_name': 'Operación de riesgo',
                'verbose_name_plural': 'Operaciones de riesgo',
                'ordering': ['entidad__nombre', 'codigo_operacion'],
            },
        ),
        migrations.CreateModel(
            name='RiskAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alerta', models.DateField(db_index=True)),
                ('tipo_alerta', models.CharField(max_length=50)),
                ('severidad', models.CharField(max_length=30)),
                ('mensaje', models.TextField()),
                ('activa', models.BooleanField(default=True)),
                ('origen', models.CharField(blank=True, max_length=100)),
                ('detalle_json', models.JSONField(blank=True, default=dict)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_riesgo', to='wcgone_core.entidad')),
                ('operacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='wcgone_risk.riskoperacion')),
            ],
            options={
                'verbose_name': 'Alerta de riesgo',
                'verbose_name_plural': 'Alertas de riesgo',
                'ordering': ['-fecha_alerta', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ContactoCobranza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_contacto', models.CharField(max_length=50)),
                ('resultado', models.CharField(blank=True, max_length=255)),
                ('acuerdo', models.TextField(blank=True)),
                ('fecha_compromiso', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos_cobranza', to='wcgone_core.contacto')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_cobranza', to='wcgone_core.entidad')),
                ('operacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos_cobranza', to='wcgone_risk.riskoperacion')),
            ],
            options={
                'verbose_name': 'Contacto de cobranza',
                'verbose_name_plural': 'Contactos de cobranza',
                'ordering': ['-fecha', 'entidad__nombre'],
            },
        ),
        migrations.CreateModel(
            name='RiskOperationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_snapshot', models.DateField(db_index=True)),
                ('record_date_raw', models.CharField(blank=True, max_length=100)),
                ('estado_operacion', models.CharField(blank=True, max_length=100)),
                ('producto_nombre_raw', models.CharField(blank=True, max_length=100)),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('capital_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('outstanding_installments', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('interest_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('insurance_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('other_charges_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('past_due_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('due_days', models.IntegerField(blank=True, null=True)),
                ('purchase_option_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('initial_rent_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_rent_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('archivo_origen', models.CharField(blank=True, max_length=255)),
                ('payload_raw_json', models.JSONField(blank=True, default=dict)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_snapshots', to='wcgone_core.entidad')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_snapshots', to='wcgone_core.dataimportbatch')),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='wcgone_risk.riskoperacion')),
            ],
            options={
                'verbose_name': 'Snapshot operativo de riesgo',
                'verbose_name_plural': 'Snapshots operativos de riesgo',
                'ordering': ['-fecha_snapshot', 'operacion_id'],
            },
        ),
        migrations.CreateModel(
            name='RiskPagoProgramado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateField()),
                ('monto_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('monto_interes', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('monto_mora', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('monto_otros', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('moneda', models.CharField(blank=True, max_length=10)),
                ('estado', models.CharField(blank=True, max_length=50)),
                ('notas', models.TextField(blank=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_programados', to='wcgone_core.entidad')),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_programados', to='wcgone_risk.riskoperacion')),
            ],
            options={
                'verbose_name': 'Pago programado',
                'verbose_name_plural': 'Pagos programados',
                'ordering': ['fecha_programada'],
            },
        ),
        migrations.CreateModel(
            name='RiskPagoRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('monto_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('monto_interes', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('monto_mora', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('monto_otros', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('moneda', models.CharField(blank=True, max_length=10)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('notas', models.TextField(blank=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_realizados', to='wcgone_core.entidad')),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_realizados', to='wcgone_risk.riskoperacion')),
            ],
            options={
                'verbose_name': 'Pago realizado',
                'verbose_name_plural': 'Pagos realizados',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='EstadoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_corte', models.DateField()),
                ('auditor_contador', models.CharField(blank=True, max_length=255)),
                ('ventas', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('utilidad_neta', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('activo_corriente', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('activo_no_corriente', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('pasivo_corriente', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('pasivo_no_corriente', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('patrimonio', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('ebitda', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_financieros', to='wcgone_core.entidad')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estados_financieros', to='wcgone_core.dataimportbatch')),
            ],
            options={
                'verbose_name': 'Estado financiero',
                'verbose_name_plural': 'Estados financieros',
                'ordering': ['-fecha_corte', 'entidad__nombre'],
                'indexes': [models.Index(fields=['entidad', 'fecha_corte'], name='risk_estado_entidad_bee549_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='riskoperacion',
            constraint=models.UniqueConstraint(fields=('entidad', 'codigo_operacion'), name='uniq_risk_operacion_entidad_codigo'),
        ),
        migrations.AddConstraint(
            model_name='riskoperationsnapshot',
            constraint=models.UniqueConstraint(fields=('operacion', 'fecha_snapshot'), name='uniq_risk_snapshot_operacion_fecha'),
        ),
    ]
