# Generated by Django 5.0 on 2026-07-15 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wcgone_risk', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='estadofinanciero',
            new_name='wcgone_risk_entidad_a3dd96_idx',
            old_name='risk_estado_entidad_bee549_idx',
        ),
    ]
